"""Constants for the BK215 hybrid controller integration."""

from __future__ import annotations

from datetime import timedelta

from homeassistant.const import Platform

DOMAIN = "bk215_hybrid_controller"

DEFAULT_NAME = "BK215 Hybrid Controller by JPS"

DEFAULT_CHARGE_LIMIT_START = 10.0
DEFAULT_INTERVAL_SECONDS = 3
DEFAULT_MAX_POWER_INVERTER = 800.0
DEFAULT_MAX_POWER_INVERTER_LIMIT = 800.0
DEFAULT_MIN_POWER_INVERTER = 0.0
DEFAULT_MIN_POWER_INVERTER_LIMIT = 600.0
DEFAULT_OFFSET = 0.0
DEFAULT_BUFFER_SOC = 3.0
DEFAULT_DEADBAND_MIN = -20.0
DEFAULT_DEADBAND_MAX = 20.0
DEFAULT_HOLD_TIME = 30

DEFAULT_KP_MIN = 0.4
DEFAULT_KP_MAX = 0.9
DEFAULT_KP_ERROR_SCALE = 600.0
DEFAULT_KI = 0.02
DEFAULT_KD = 0.12
DEFAULT_KD_ERROR_SCALE = 300.0
DEFAULT_KD_DT_REF = 3.0
DEFAULT_KD_MAX = 0.35

# PID defaults for dual-tower setups
DEFAULT_KP_MAX_2T = 0.65
DEFAULT_KI_2T = 0.06
DEFAULT_KD_2T = 0.55
DEFAULT_KD_DT_REF_2T = 2.0

DEFAULT_DT_CLAMP_THRESHOLD = 15.0
DEFAULT_DT_DEFAULT = 2.0
BOOST_POST_CYCLE_DELAY = 1.0
PID_POST_CYCLE_DELAY = 2.0
DEYE_BOOST_HYSTERESIS = 0.5
DEYE_PID_HYSTERESIS = 0.2
APSYSTEMS_HYSTERESIS = 5.0
DEFAULT_INTEGRAL_LIMIT_PCT = 0.3

MIN_APSYSTEMS_POWER_SINGLE = 30.0
MIN_APSYSTEMS_POWER_DUAL = 60.0

PLATFORMS: list[Platform] = [
    Platform.BINARY_SENSOR,
    Platform.NUMBER,
    Platform.SENSOR,
    Platform.SWITCH,
]

UPDATE_DEBOUNCE = timedelta(milliseconds=150)
